# Generated by Django 5.2.5 on 2025-09-04 18:06

import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('contact_request', 'Contact Request'), ('property_view', 'Property View'), ('new_message', 'New Message'), ('system_alert', 'System Alert'), ('promotion', 'Promotion')], max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.upload_to_app_model)),
                ('is_read', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
    ]
