# Generated by Django 5.2.5 on 2025-09-06 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.IntegerField()),
                ('length', models.IntegerField()),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_ranges', to='notifications.notification')),
            ],
            options={
                'db_table': 'Range',
            },
        ),
    ]
