# Generated by Django 5.2.5 on 2025-09-06 09:35

import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image_representation',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=apps.utils.upload_to_app_model),
        ),
    ]
