# Generated by Django 5.2.5 on 2025-11-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='range',
            table='range',
        ),
    ]
