# Generated by Django 5.2.5 on 2025-08-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contactrequest_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='updated_at',
        ),
    ]
