# Generated by Django 5.2.5 on 2025-11-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contactrequest_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactrequest',
            table='contactrequest',
        ),
    ]
