# Generated by Django 5.2.5 on 2025-11-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboard',
            table='dashboard',
        ),
        migrations.AlterModelTable(
            name='predictrequest',
            table='predictrequest',
        ),
    ]
