# Generated by Django 5.2.5 on 2025-11-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0002_alter_dashboard_table_alter_predictrequest_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='countRemain',
            field=models.IntegerField(default=100),
        ),
    ]
