# Generated by Django 5.2.5 on 2025-11-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('private', 'private'), ('group', 'group')], default='private', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_1_to_1_index', models.CharField(db_index=True, default=None, max_length=40, null=True, unique=True)),
            ],
            options={
                'db_table': 'conversation',
            },
        ),
    ]
