# Generated by Django 5.2.5 on 2025-08-09 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defaults', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('decription', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=255)),
                ('coord_x', models.DecimalField(decimal_places=20, max_digits=20)),
                ('coord_y', models.DecimalField(decimal_places=20, max_digits=20)),
                ('bedrooms', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('frontage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('legal_status', models.IntegerField(choices=[('sổ đỏ', 1), ('sổ hồng', 1), ('hợp đồng', 2)], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='defaults.district')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='defaults.propertytype')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='defaults.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='./static/property_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
