# Generated by Django 5.2.5 on 2025-08-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='Property',
        ),
        migrations.AlterModelTable(
            name='propertyimage',
            table='PropertyImage',
        ),
    ]
