# Generated by Django 5.2.5 on 2025-08-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_table_alter_propertyimage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='./static/property_thumbnails'),
        ),
    ]
