# Generated by Django 5.2.5 on 2025-08-10 15:17

import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='coord_x',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='coord_y',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='legal_status',
            field=models.IntegerField(choices=[(1, 'sổ đỏ'), (1, 'sổ hồng'), (2, 'hợp đồng')], default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.upload_to_app_model),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=apps.utils.upload_to_app_model),
        ),
    ]
