# Generated by Django 5.2.5 on 2025-08-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_deleted_at_alter_property_coord_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='coord_x',
            field=models.DecimalField(decimal_places=15, max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='coord_y',
            field=models.DecimalField(decimal_places=15, max_digits=15),
        ),
    ]
