# Generated by Django 5.2.5 on 2025-08-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_bedrooms_alter_property_floors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='coord_x',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='coord_y',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
