# Generated by Django 5.2.5 on 2025-08-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_coord_x_alter_property_coord_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
