# Generated by Django 5.2.5 on 2025-08-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='decription',
            new_name='description',
        ),
    ]
