# Generated by Django 5.2.5 on 2025-08-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_rename_decription_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status_sell',
            field=models.CharField(choices=[('thue', 'Cho thuê'), ('ban', 'Bán')], default='ban', max_length=10),
        ),
    ]
