# Generated by Django 5.2.5 on 2025-08-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_status_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='status_sell',
            new_name='tab',
        ),
    ]
