# Generated by Django 5.2.5 on 2025-11-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_property_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='property',
        ),
        migrations.AlterModelTable(
            name='propertyimage',
            table='propertyimage',
        ),
    ]
