# Generated by Django 5.2.5 on 2025-11-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_property_table_alter_propertyimage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tab',
            field=models.CharField(choices=[('thue', 'thue'), ('ban', 'ban')], default='ban', max_length=10),
        ),
    ]
