# Generated by Django 5.2.5 on 2025-11-17 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0006_attribute_alter_district_code_alter_province_code_and_more'),
        ('properties', '0014_alter_property_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='defaults.attribute')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='properties.property')),
            ],
            options={
                'db_table': 'property_attribute_value',
            },
        ),
    ]
