# Generated by Django 5.2.5 on 2025-11-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0007_alter_propertytype_attribute_unique_together'),
        ('properties', '0015_propertyattributevalue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertyattributevalue',
            unique_together={('property', 'attribute')},
        ),
    ]
