# Generated by Django 5.2.5 on 2025-11-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_propertyattributevalue_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'Đợi duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối')], default='approved', max_length=20),
        ),
    ]
