# Generated by Django 5.2.5 on 2025-12-09 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_property_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_property', to='properties.property')),
            ],
            options={
                'db_table': 'views_property',
            },
        ),
    ]
