# Generated by Django 5.2.5 on 2025-08-19 10:57

import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='/accounts/default/user_avatar.png', null=True, upload_to=apps.utils.upload_to_app_model),
        ),
    ]
