# Generated by Django 5.2.5 on 2025-08-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
