# Generated by Django 5.2.5 on 2025-08-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
