# Generated by Django 5.2.5 on 2025-09-16 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0003_district_deleted_at_propertytype_deleted_at_and_more'),
        ('news', '0003_comment_is_deleted_newsarticle_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='defaults.province'),
        ),
    ]
