# Generated by Django 5.2.5 on 2025-09-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsarticle_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='news_thumbnails/'),
        ),
    ]
