# Generated by Django 5.2.5 on 2025-09-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsarticle_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
