# Generated by Django 5.2.5 on 2025-09-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsarticle_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
