# Generated by Django 5.2.5 on 2025-09-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsarticle_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
