# Generated by Django 5.2.5 on 2025-11-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_delete_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsarticle',
            table='newsarticle',
        ),
    ]
