# Generated by Django 5.2.5 on 2025-08-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='district',
            table='District',
        ),
        migrations.AlterModelTable(
            name='propertytype',
            table='PropertyType',
        ),
        migrations.AlterModelTable(
            name='province',
            table='Province',
        ),
    ]
