# Generated by Django 5.2.5 on 2025-09-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0003_district_deleted_at_propertytype_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='tab',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
