# Generated by Django 5.2.5 on 2025-11-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0004_propertytype_tab'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='district',
            table='district',
        ),
        migrations.AlterModelTable(
            name='propertytype',
            table='propertytype',
        ),
        migrations.AlterModelTable(
            name='province',
            table='province',
        ),
    ]
