# Generated by Django 5.2.5 on 2025-11-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0006_attribute_alter_district_code_alter_province_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertytype_attribute',
            unique_together={('attribute', 'property_type')},
        ),
    ]
