# Generated by Django 5.2.5 on 2025-11-09 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_cart', '0002_alter_favouriteproperty_user'),
        ('properties', '0013_alter_property_table_alter_propertyimage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_properties', to='properties.property'),
        ),
        migrations.AlterModelTable(
            name='favouriteproperty',
            table='favouriteproperties',
        ),
    ]
